README.md
various small copy edits to improve readability and touch on the awesome `~/.ssh/config` stuff a little more.
=> docs: copy edits

client.go, cmd/wishlist/main.go, middleware.go, server.go, sshconfig/parse.go
fixed what made sense, ignored others.
most errs are wrapped up in the call chain, so no need to wrap before as well
=> fix: linter issues

.github/workflows/build.yml
reuse from https://github.com/charmbracelet/meta/blob/main/.github/workflows/snapshot.yml
=> feat: reuse snapshot from meta

config.go, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good.ssh_config
refs #20 
parses the `ForwardAgent` option
=> feat: parse forward agent

client_auth.go, client_local.go
reuse the same connection for auth and agent forwarding, and clean it up when done.
=> fix: improve local agent usage

cmd/wishlist/main.go
this allows to run `wishlist endpoint-name` to connect directly to a given endpoint.
=> feat: allow to bypass the list

client_auth.go
better/more logs about which auth methods are being uses, including key type and sha256.
=> fix: improve client logs

client_auth.go, go.mod, go.sum, middleware.go
Update and use the new features
pending wish release to use a fixed version
=> feat: update wish

blocking/reader.go, blocking/reader_test.go
it was extracted from the main package and after that it could have been simplified a lot.
this pr does that :)
=> refactor: simplify blocking reader

wishlist.go, wishlist_test.go
- do not quit wishlist on error anymore
- better styles in the error view
- show only the root error in the error view
=> feat: improve error handling

README.md
=> Re-record Gif using Charm theme

wishlist.go
=> fix: dont connect using "o" while setting a filter

.goreleaser.yml, scripts/completions.sh, scripts/manpages.sh
Use the same scripts as in https://github.com/charmbracelet/soft-serve/pull/127 and https://github.com/charmbracelet/skate/pull/40
=> chore: update scripts to match other projects

README.md
=> Fixes #105

client.go, client_local.go, client_remote.go
This will allow to cancel an ongoing connection and go back to the list, on local mode only for now.
refs #108
=> feat: allow to abort pending conn

_example/config, _example/config.yaml, client_local.go, client_remote.go, cmd/wishlist/main_test.go, config.go, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good, wishlist.go
refs https://github.com/charmbracelet/wishlist/issues/108
=> feat: allow to set connect timeout

blocking/reader.go
=> docs: improve godoc

blocking/reader.go, client.go, client_auth.go, client_local.go, cmd/wishlist/main.go, server.go, sshconfig/parse.go, wishlist.go
handle an error parsing timeouts, and fixed lint issues.
=> fix: missing err handling, lint issues

multiplex/reader.go, multiplex/reader_test.go
bytes.Buffer are not thread safe, so we need to wrap the writes/reads/etc with a mutex.
also improved the `first` thingy while I'm at it.
=> fix: race condition in multiplex/writer

wishlist.go
=> fix: error message wrapping

_example/main.go, client.go, client_agent.go, client_auth.go, client_local.go, client_remote.go, client_signals_unix.go, cmd/wishlist/main.go, config.go, go.mod, go.sum, middleware.go, multiplex/reader.go, server.go, srv/srv.go, wishlist.go, zeroconf/zeroconf.go
=> feat: use charm/log

server.go
ignore server closed errors, use log.Info
=> fix: properly handle server shutdown

README.md
=> docs: document supported options

client_auth.go, client_auth_test.go, cmd/wishlist/main.go, go.mod, go.sum
=> feat(deps): update wish and keygen

_example/main.go
=> docs: fix example
