server.go
Instead of initiating a connection to a potentially running service, try to actually `net.Listen` on the specified ports to find the first available one.
=> Find available ports by trying to listen on it

sshconfig/parse.go
Safe to ignore this error, we don't write to this file.
=> Ignore error returned from closing r/o file

_example/config.ssh_config, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good.ssh_config
```
Host ssh.foo.bar
```
will now evaluate to 
```yaml
- name: ssh.foo.bar
address: ssh.foo.bar:22
```
also removed a log and improved the example a bit.
=> fix: parsing ssh config when Host only

wishlist.go
Adds a small check to avoid an exception that crashes the client when hitting enter when no items are available.
https://user-images.githubusercontent.com/1270156/149637506-be1da8f1-47ac-41d9-878f-5974006539da.mp4
An edge case, yes, but figured that avoids the crash and the client being disconnected, which provides a better UX overall.
With the patch, run the server, connect with a client and hit enter. It should not raise an exception neither the client should be disconnected.
Complete log of the panic.
```shell
2022/01/15 22:00:06 Using config from /etc/ssh/ssh_config
2022/01/15 22:00:06 Starting SSH server for list on ssh://0.0.0.0:2222
2022/01/15 22:00:08 kinduff connect 127.0.0.1:38484 false [] xterm-256color 44 29
Caught panic:
interface conversion: list.Item is nil, not …
```
=> Verifies if the selected item exists

config.go, go.mod, go.sum, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good.ssh_config, sshconfig/testdata/include.ssh_config, sshconfig/testdata/included.ssh_config
this allows to parse `Include` statements on ssh config files, as well as deal with globs.
Testing how SSH parses, it seems like its in order... so this should do more or less the same thing.
=> feat: parse Include, IdentityFile and wildcards

.gitignore, README.md, client.go, client_auth.go, client_auth_test.go, client_local.go, client_remote.go, client_signals_unix.go, client_signals_windows.go, client_test.go, cmd/wishlist/main.go, config.go, go.mod, go.sum, home/expand.go, home/expand_test.go, middleware.go, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good.ssh_config, sshconfig/testdata/include.ssh_config, wishlist.go
Allow wishlist to run locally, meaning it'll be just an interface for the config file.
When you run with `--local`, you'll go directly to the TUI, and can then browse/SSH into your SSH targets from `~/.ssh/config`
=> feat: add a --local flag

README.md, _example/config.ssh_config, _example/config.yaml, client.go, client_auth.go, client_local.go, client_remote.go, config.go
- use `RemoteCommand` on remote mode
- use `ForwardAgent` on remote mode (which will forward further the previously forwarded agent, if any)
- Allow those options in the yaml config as well
=> feat: uses RemoteCommand and ForwardAgent when using remote mode as well

cmd/wishlist/main.go, sshconfig/parse.go, sshconfig/testdata/good
this is to avoid the upstream ssh_parse lib panicking.
=> fix: parse config with Match

_example/config.yaml, client.go, config.go, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good
- parse ssh config `SendEnv` and `SetEnv` 
- allow an `environment` config in the yaml
- passes environment variables into the session
closes #68
=> feat: allow to setenv and sendenv

_example/config.yaml, client.go, client_local.go, client_remote.go, config.go, config_test.go, sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good
refs #68 #70 
Make it better by splitting `SetEnv` and `SendEnv` in the YAML config as well, and properly handling `SetEnv` (it should set the env wether or not it is in `SendEnv`), as well as using `os.Environ()` and the parent's `session.Environ()` on clients (in that case allowing only the keys in `SendEnv`).
todo: 
this will make it more like the openssh client.
=> feat: pass allowed env from parent connection

_example/config.yaml, config.go
The remote client does not use that field, wheter its set or not. Only the local client uses it. That said, it should be safe to allow it in the yaml config as well.
closes #60
=> feat: yaml accept identity_files in local mode

_example/config.yaml, listitem.go, listitem_test.go, wishlist.go, wishlist_test.go
When setting the items in the list, check which features we use (i.e. links, descriptions, etc), size up the items accordingly and show a placeholder in items missing any of those items.
=> fix: smarter list delegate height

wishlist.go
This fixes a small issue, where wishlist went in a quitting state, if the user pressed "esc" to cancel setting a filter.
=> fix: dont quit if filter is getting applied

wishlist.go
I noticed a bug that prevented the clearing of a filter using "esc". 
The code could be simplified slightly if https://github.com/charmbracelet/bubbles/pull/98 gets merged.
=> fix: dont quit if filter is set

cmd/wishlist/main.go, cmd/wishlist/main_test.go
alternative fix for running wishlist as root when neither `$XDG_CONFIG_HOME` nor `$HOME` are defined by `os.UserConfigDir()`
closes #103
=> fix: handle no HOME and no XDG_CONFIG_HOME

client.go
When using wishlist as a library for multiple tea apps, since the "return to the list" feature, it seems that the app might not properly exit the session, which causes it to display an error.
Its not an useful error anyway, so it should be safe to ignore it.
=> fix: ignore if the tea app didnt report an exit status

_example/config.yaml, config.go, server.go
Hi, since 8e35697fff3174fdffc8e52e90503d3845830b42 wishlist always starts a metrics server. Adding metrics is an amazing idea, however not everyone needs that and therefore I'd like to propose to make this feature optional.  
If you want it enabled by default, I'd suggest to at least add a `disabled` option.
=> feat: make metrics optional

README.md, cmd/wishlist/main.go, srv/srv.go, srv/srv_test.go, zeroconf/zeroconf.go
allow to find entrypoints from `_ssh._tcp.DOMAIN` SRV records.
refs #135
---
to try it out, create a DNS entry in a domain you own, for example `_ssh._tcp.caarlos0.dev`. 
You can set any priorities and weights, wishlist will just list them all.
Then, you can use `dig` to verify it works, e.g.:
```sh
dig -t SRV _ssh._tcp.caarlos0.dev +short
1 1 22 s01.caarlos0.dev.                                                                                                                                                                                                                                             
10 2 2222 s01.caarlos0.dev.
```
You can also customize the name of the endpoints by adding TXT records to the domain root, e.g.:
```sh
dig -t TXT caarlos0.dev +short
"wishlist.name …
```
=> feat: discover from DNS SRV records

client.go
OpenSSH also seems to only warn (judging by several stackoverflow posts, couldn't reproduce) when setting an environment variable fails.
I believe we can do the same on wishlist.
This refs #151
=> fix: warn if setenv fails instead of hard-erroring

sshconfig/parse.go
OpenSSH doesn't error on it... so we might ignore it as well...
=> fix: do not hard-error if included file does not exist

client_auth.go, client_remote.go
This PR adds keyboard-interactive auth method to both local and remote clients.
**Limitations**:
- remote client will never echo anything because stdin is not in fact the stdin, but the parent's session stdin, which we don't have a `fd` for. It looks like [this](https://cln.sh/Dl8DJGr4)
refs #186
=> feat: support keyboard-interactive

README.md, _example/config.yaml, cmd/wishlist/main.go, cmd/wishlist/main_test.go, config.go
Hints can be used to "hint" options into endpoints discovered though other means, for instance, zeroconf.
Wishlist will match the `hint.match` (as a glob) against the discovered endpoints' names, and will apply the given settings to said endpoints.
It'll only apply to discovered endpoints, and will not affect other endpoints.
This can only be set via YAML configuration.
=> feat: hints

.golangci-soft.yml, client.go, cmd/wishlist/main.go, config.go
fixed small-ish linting issues
=> fix: lint issues

README.md, cmd/wishlist/main.go, tailscale/tailscale.go
- added tailscale tailnet discovery
- several readme updates
=> feat: tailscale integration

cmd/wishlist/main.go, srv/srv.go, zeroconf/zeroconf.go
using the cobra's context down into zeroconf and srv discoveries
=> fix: use context on zeroconf and srv

.github/dependabot.yml, sshconfig/parse.go, sshconfig/testdata/good
fixes #207
we're checking strictly `HostName`, so `Hostname` wasn't getting parsed properly.
This lowercases the key and checks it against the lowercased keywords, which seems more similar to what openssh does.
=> fix: sshconfig parse: lowercase keys

multiplex/reader.go
`sync.RWMutex` allows concurrent reads, which apparently the inner `bytes.Buffer` don't, and wishlist was triggering sometimes. 
So, changing to a `sync.Mutex` thus locking all ops fixes it.
Thanks @aymanbagabas for reporting this!
=> fix: race condition in server mode

tailscale/tailscale.go
Tailscale nodes are more commonly known by their Tailscale device name, rather than the hostname. [Tailscale suggests using the device name/MagicDNS name too, to connect over SSH](https://tailscale.com/kb/1193/tailscale-ssh/#connect-over-ssh). This PR updates the displayed name to the device name for convenience.
| Before | After |
|--------|--------|
| <img width="1590" alt="image" src="https://github.com/charmbracelet/wishlist/assets/18581859/c8f61500-3be4-4a2e-8da6-fe1876032873"> | <img width="1590" alt="image" src="https://github.com/charmbracelet/wishlist/assets/18581859/f65a109d-15b2-46a8-9ca5-9498647e7902"> |
=> feat(tailscale): update hostname to device name

cmd/wishlist/main.go
closes #217
In server mode, we log the errors, so we don't need to print them again (hence `SilenceErrors`), but on local mode we don't log them, so we shouldn't silence errors in the case.
=> fix: handle errors on local mode

client_local.go, client_unix.go, client_windows.go
apparently windows does not handle it very well... and it seems to not be needed for windows either way.
closes #102
=> fix: do not make raw terminal on windows

README.md
This PR fixes the example for Windows with scoop using the wrong syntax. 
The scoop add command also requires a name for the bucket: 
```bash
Unknown bucket 'https://github.com/charmbracelet/scoop-bucket.git'. Try specifying <repo>.
usage: scoop bucket add <name> [<repo>]
```
This was not included in the example, so the command would fail. I set the name to `charm` in this PR.
=> Update README.md to fix scoop command

sshconfig/parse.go, sshconfig/parse_test.go, sshconfig/testdata/good
This should work, and the quotes should be ignored.
=> fix: SetEnv when quoted value

wishlist.go
=> feat: copy address to the clipboard
